/// English localization strings stored as a lookup map
class AppStringsEn {
  static const Map<String, String> values = {
    'appName': "Syria Store",
    'appDescription': "Your one-stop shop for all your needs in Syria",
    'headerMessage1': "Shop exclusive collections for every occasion.",
    'headerMessage2': "Get the best deals on your favorite brands.",
    'headerMessage3': "Refresh your style with our handpicked selection.",
    'headerMessage4': "Discover the latest fashion trends.",
    'headerMessage5': "Enjoy fast shipping and unbeatable prices.",
    'headerMessage6': "Find statement pieces for every season.",
    'headerMessage7': "Elevate your everyday essentials in style.",
    'language': "Language",
    'darkMode': "Dark Mode",
    'currencyDisplay': "Currency Display",
    'showEquivalent': "Show Equivalent",
    'notificationsEnabled': "Enable Notifications",
    'about': "About",
    'version': "Version",
    'contactUs': "Contact Us",
    'whatsapp': "WhatsApp",
    'call': "Call",
    'businessHours': "Business Hours",
    'workingDays': "Sunday - Thursday",
    'supportMessage': "Hello, I need help with my order",
    'faq': "FAQ",
    'termsOfServiceTitle': "Syria Store Terms of Service",
    'termsOfServiceIntro':
        "Welcome to Syria Store. By using our services, you agree to these terms and conditions. Please read them carefully.",
    'accountTermsTitle': "Account Terms",
    'accountTermsContent':
        "You must be over 18 years old to create an account. You are responsible for maintaining the confidentiality of your account and password.",
    'purchaseTermsTitle': "Purchase Terms",
    'purchaseTermsContent':
        "When you place an order, you are making an offer to purchase the products. We reserve the right to refuse or cancel any order for any reason.",
    'deliveryTermsTitle': "Delivery Terms",
    'deliveryTermsContent':
        "We provide delivery service throughout Syria. Delivery times are estimates and may vary depending on location and circumstances.",
    'cancellationTermsTitle': "Cancellation Terms",
    'cancellationTermsContent':
        "You may cancel your order before it is shipped. Once shipped, our return policy applies.",
    'privacyTermsTitle': "Privacy",
    'privacyTermsContent':
        "We respect your privacy and protect your personal data according to our Privacy Policy.",
    'changesTermsTitle': "Changes to Terms",
    'changesTermsContent':
        "We reserve the right to update these terms at any time. You will be notified of any material changes.",
    'termsLastUpdated': "Last updated: October 1, 2025",
    'privacyPolicyTitle': "Privacy Policy",
    'privacyPolicyIntro':
        "We value your privacy and are committed to protecting your personal data. This policy explains how we collect, use, and protect your information.",
    'dataCollectionTitle': "Data Collection",
    'dataCollectionContent':
        "We collect information you provide directly to us, such as your name, address, and contact details, as well as information about your use of the app.",
    'dataUsageTitle': "Data Usage",
    'dataUsageContent':
        "We use your data to provide our services, process your orders, and communicate with you about your orders and our offers.",
    'dataProtectionTitle': "Data Protection",
    'dataProtectionContent':
        "We implement appropriate security measures to protect your data against unauthorized access, alteration, or disclosure.",
    'cookiesTitle': "Cookies",
    'cookiesContent':
        "We use cookies to improve your experience in the app and to personalize content and advertisements.",
    'thirdPartyTitle': "Third Parties",
    'thirdPartyContent':
        "We may share your data with certain service providers to facilitate our services, such as shipping and payment processing companies.",
    'privacyLastUpdated': "Last updated: October 1, 2025",
    'returnPolicyTitle': "Return Policy",
    'returnPolicyIntro':
        "We want you to be completely satisfied with your purchases. This policy explains how to return products and receive refunds.",
    'eligibilityTitle': "Return Eligibility",
    'eligibilityContent':
        "Products can be returned within 7 days of receipt, provided they are in their original condition with all tags and packaging.",
    'processTitle': "Return Process",
    'processContent':
        "To initiate a return, please contact customer service. We will arrange for the product to be collected and inspected.",
    'refundsTitle': "Refunds",
    'refundsContent':
        "Once the return is approved, the refund will be processed to your original payment method within 14 business days.",
    'nonReturnableTitle': "Non-Returnable Items",
    'nonReturnableContent':
        "Some items are non-returnable for health and safety reasons, such as opened personal care products.",
    'damagesTitle': "Damaged Items",
    'damagesContent':
        "If you receive a damaged item, please notify us within 24 hours of receipt. We will arrange for a replacement or refund.",
    'returnLastUpdated': "Last updated: October 1, 2025",
    'loading': "Loading...",
    'error': "Error",
    'retry': "Retry",
    'cancel': "Cancel",
    'confirm': "Confirm",
    'save': "Save",
    'edit': "Edit",
    'delete': "Delete",
    'add': "Add",
    'remove': "Remove",
    'search': "Search",
    'filter': "Filter",
    'sort': "Sort",
    'clear': "Clear",
    'apply': "Apply",
    'next': "Next",
    'previous': "Previous",
    'done': "Done",
    'close': "Close",
    'back': "Back",
    'home': "Home",
    'profile': "Profile",
    'profileLoadErrorTitle': "We could not load your profile",
    'profileLoadErrorMessage': "Please try again in a moment.",
    'profileMemberSince': "Member since 2023",
    'profileStatsOrders': "Orders",
    'profileStatsFavorites': "Favorites",
    'profileStatsVouchers': "Vouchers",
    'profileFitPreferences': "Fit preferences",
    'profileStyleInspiration': "Style inspiration",
    'profilePaletteFavourites': "Palette favourites",
    'profileStyleSmartCasual': "Smart casual",
    'profileStyleStreetwear': "Streetwear",
    'profileStyleActivewear': "Activewear",
    'profileStyleMinimalist': "Minimalist",
    'profileStyleTraditional': "Traditional",
    'profileColorEarthTones': "Earth tones",
    'profileColorNeutrals': "Neutrals",
    'profileColorBoldColours': "Bold colours",
    'profileColorPastels': "Pastels",
    'profileDarkModeSubtitle': "Switch between light and dark for the entire app.",
    'profileQuickLinks': "Quick links",
    'profileEditButton': "Edit",
    'profileSavedFavouritesTitle': "Saved favourites",
    'profileSavedFavouritesDescription': "48 pieces you are tracking",
    'profileDeliveryAddressesTitle': "Delivery addresses",
    'profileDeliveryAddressesDescription': "Home / Work / Parents",
    'profileOrdersReturnsTitle': "Orders & returns",
    'profileOrdersReturnsDescription': "Track deliveries and past purchases",
    'profileAccountSettingsTitle': "Account settings",
    'profileAccountSettingsDescription': "Password, notifications & currency",
    'profileSignOutLabel': "Sign out",
    'profileSignOutMessage': "Signed out successfully (mock).",
    'currencyNameSYP': "Syrian Pound",
    'currencyNameUSD': "US Dollar",
    'currencyNameTRY': "Turkish Lira",
    'homeCurrencyButtonLabel': "Change currency",
    'homeCurrencySheetTitle': "Choose currency",
    'homeCurrencySheetSubtitle': "Display product prices in your preferred currency.",
    'homeCurrencySheetCancel': "Cancel",
    'settings': "Settings",
    'notifications': "Notifications",
    'globalPreferencesComingSoon': "Global preferences coming soon.",
    'currencySelectionComingSoon': "Currency selection coming soon.",
    'comingSoonGeneric': "Coming soon. Stay tuned!",
    'cart': "Cart",
    'cartUnavailableTitle': "Cart temporarily unavailable",
    'cartUnavailableMessage': "Please try again in a moment.",
    'cartEmptyTitle': "Your cart is empty",
    'cartEmptyMessage': "Add some products to get started.",
    'cartOnTheWayTitle': "On the way",
    'cartAwesomeButton': "Awesome!",
    'cartProcessingOrder': "Processing order...",
    'orders': "Orders",
    'categories': "Categories",
    'categoryWomen': "Women",
    'categoryMen': "Men",
    'categoryBoys': "Boys",
    'categoryGirls': "Girls",
    'categoryBaby': "Baby",
    'categoryBeauty': "Beauty",
    'categoryGifts': "Gifts",
    'products': "Products",
    'favorites': "Favorites",
    'favoritesUnavailableTitle': "Favorites unavailable",
    'favoritesUnavailableMessage':
        "We ran into a problem loading your favorites.",
    'favoritesHeaderSubtitleEmpty':
        "Keep exploring and save pieces you love for quick access.",
    'favoritesHeaderSubtitleSingular': "You have {count} saved piece.",
    'favoritesHeaderSubtitlePlural': "You have {count} saved pieces.",
    'favoritesClearConfirmTitle': "Clear favorites?",
    'favoritesClearConfirmMessage':
        "This will remove every saved product from your favorites list.",
    'favoritesExploreButton': "Explore home",
    'favoritesClearButton': "Clear all",
    'favoritesEmptyTitle': "No favorites yet",
    'favoritesEmptyMessage':
        "Tap the heart on any product to save it here. We picked some ideas to get you started.",
    'favoritesSuggestionsTitle': "You might also like",
    'favoritesSuggestionsOfflineTitle': "Recommendations offline",
    'favoritesSuggestionsOfflineMessage':
        "Pull to refresh to try loading suggestions again.",
    'favoritesSuggestionsEmptyTitle': "Nothing to show right now",
    'favoritesSuggestionsEmptyMessage':
        "Check back soon for fresh picks tailored to your taste.",
    'price': "Price",
    'quantity': "Quantity",
    'total': "Total",
    'subtotal': "Subtotal",
    'delivery': "Delivery",
    'discount': "Discount",
    'coupon': "Coupon",
    'applyCoupon': "Apply Coupon",
    'couponCode': "Coupon Code",
    'validCoupon': "Valid Coupon",
    'invalidCoupon': "Invalid Coupon",
    'expiredCoupon': "Expired Coupon",
    'minOrderAmount': "Minimum Order Amount",
    'currency': "SYP",
    'splash': "Splash",
    'login': "Login",
    'signup': "Sign Up",
    'forgotPassword': "Forgot Password",
    'productDetails': "Product Details",
    'productList': "Product List",
    'checkout': "Checkout",
    'addressBook': "Address Book",
    'orderDetails': "Order Details",
    'customerSupport': "Customer Support",
    'termsOfService': "Terms of Service",
    'privacyPolicy': "Privacy Policy",
    'returnPolicy': "Return Policy",
    'phoneNumber': "Phone Number",
    'email': "Email",
    'password': "Password",
    'confirmPassword': "Confirm Password",
    'otpCode': "OTP Code",
    'sendOtp': "Send OTP",
    'verifyOtp': "Verify OTP",
    'resendOtp': "Resend OTP",
    'loginSuccess': "Login Successful",
    'signupSuccess': "Sign Up Successful",
    'logout': "Logout",
    'address': "Address",
    'governorate': "Governorate",
    'city': "City",
    'area': "Area",
    'street': "Street",
    'building': "Building",
    'floor': "Floor",
    'apartment': "Apartment",
    'notes': "Notes",
    'defaultAddress': "Default Address",
    'addAddress': "Add Address",
    'editAddress': "Edit Address",
    'selectAddress': "Select Address",
    'addressEmptyMessage': "Tap the add button to save your first address.",
    'orderNumber': "Order Number",
    'orderDate': "Order Date",
    'orderStatus': "Order Status",
    'orderTotal': "Order Total",
    'paymentMethod': "Payment Method",
    'paymentStatus': "Payment Status",
    'deliveryMethod': "Delivery Method",
    'deliveryDate': "Delivery Date",
    'deliveryTime': "Delivery Time",
    'orderPlaced': "Order Placed",
    'orderConfirmed': "Order Confirmed",
    'orderShipped': "Order Shipped",
    'orderDelivered': "Order Delivered",
    'orderCancelled': "Order Cancelled",
    'cashOnDelivery': "Cash on Delivery",
    'placeOrder': "Place Order",
    'orderSuccess': "Order Placed Successfully",
    'orderSuccessTitle': "Order Success",
    'orderSuccessHeadline':
        "Thank you! Your order is confirmed and now being prepared.",
    'orderSuccessFallback':
        "We can't show the order details right now, but you can track everything from the Orders tab.",
    'ordersLoadErrorTitle': "Unable to load orders",
    'ordersLoadErrorMessage': "Please check your connection and try again.",
    'noOrdersMessage': "Start shopping to add your first order.",
    'orderItemsCount': "Items",
    'deliveryFee': "Delivery fee",
    'orderPaid': "Paid",
    'orderPendingPayment': "Pending",
    'orderPlacedAt': "Order placed on",
    'viewOrders': "View orders",
    'backToHome': "Back to home",
    'damascus': "Damascus",
    'aleppo': "Aleppo",
    'homs': "Homs",
    'latakia': "Latakia",
    'hama': "Hama",
    'deirEzZor': "Deir ez-Zor",
    'raqqa': "Raqqa",
    'hasaka': "Hasaka",
    'tartus': "Tartus",
    'idlib': "Idlib",
    'quneitra': "Quneitra",
    'daraa': "Daraa",
    'sweida': "Sweida",
    'faqDeliveryTime': "How long does delivery take?",
    'faqDeliveryTimeAnswer':
        "Delivery typically takes 2-3 working days within Damascus, and 4-7 days for other governorates.",
    'faqPaymentMethods': "What payment methods are available?",
    'faqPaymentMethodsAnswer':
        "We currently accept only cash on delivery. We are working on adding electronic payment methods soon.",
    'faqReturnPolicy': "What is the return policy?",
    'faqReturnPolicyAnswer':
        "You can return the product within 7 days of receipt if it has a manufacturing defect or was damaged during shipping.",
    'chat': "Chat",
    'send': "Send",
    'networkError': "Network Error",
    'serverError': "Server Error",
    'unknownError': "Unknown Error",
    'validationError': "Validation Error",
    'notFound': "Not Found",
    'unauthorized': "Unauthorized",
    'forbidden': "Forbidden",
    'timeout': "Connection Timeout",
    'offline': "Offline",
    'noInternetConnection': "No Internet Connection",
    'noProducts': "No Products",
    'noOrders': "No Orders",
    'noNotifications': "No Notifications",
    'noAddresses': "No Addresses",
    'noCoupons': "No Coupons",
    'noSearchResults': "No Search Results",
    'emptyCart': "Cart is Empty",
    'productAddedToCart': "Product Added to Cart",
    'productRemovedFromCart': "Product Removed from Cart",
    'productAddToCartButton': "Add to Cart",
    'productAddToFavouritesButton': "Add to Favourites",
    'addressAdded': "Address Added",
    'addressUpdated': "Address Updated",
    'addressDeleted': "Address Deleted",
    'couponApplied': "Coupon Applied",
    'settingsSaved': "Settings Saved",
    'currencyEquivalent': "Show price in approximate USD",
    'languageComingSoon': "Language switcher is coming soon.",
    'aboutDescription':
        "Joud Store is a Syrian fashion platform offering the latest styles with reliable delivery.",
    'checkoutStepAddress': "Shipping Address",
    'checkoutStepDelivery': "Delivery Options",
    'checkoutStepPayment': "Payment Method",
    'checkoutStepReview': "Review Order",
    'checkoutAddressTitle': "Delivery address details",
    'checkoutAddressDescription':
        "Select or add a delivery address so we can ship your order to the right place.",
    'checkoutDeliveryTitle': "Choose delivery method",
    'checkoutDeliveryDescription':
        "Pick the delivery option that suits you best and review any extra fees or timing before confirming.",
    'checkoutPaymentTitle': "Select payment method",
    'checkoutPaymentDescription':
        "We currently support cash on delivery. Online payment methods are coming soon.",
    'checkoutReviewTitle': "Order summary",
    'checkoutSubtotalLabel': "Items total",
    'checkoutDeliveryFeeLabel': "Delivery fee",
    'checkoutTotalLabel': "Amount due",
    'checkoutEmptyMessage':
        "Your cart is empty. Add items to continue to checkout.",
    'searchTrending': "Trending searches",
    'searchRecent': "Recent searches",
    'searchClearHistory': "Clear search history",
    'searchPlaceholder': "Search for products, categories, or brands...",
    'searchHintCompact': "Search here",
    'homeSearchPrompt': "Start typing to discover new looks.",
    'searchError': "We couldn't load search results. Please try again.",
    'searchSuggestions': "Search suggestions",
    'trendSpringFreshLayers': "Light spring dresses",
    'trendSpringRamadanLooks': "Ramadan outfits",
    'trendSpringLightFabrics': "Breathable spring fabrics",
    'trendSummerLinen': "Summer linen sets",
    'trendSummerBeachwear': "Beachwear",
    'trendSummerEvening': "Summer evening dresses",
    'trendFallLayers': "Cozy fall layers",
    'trendFallEarthTones': "Earth-tone outfits",
    'trendFallBackToSchool': "Back-to-school looks",
    'trendWinterCoats': "Winter coats",
    'trendWinterKnitwear': "Warm knitwear",
    'trendWinterAccessories': "Winter accessories",
    'trendStyleCasual': "Everyday chic",
    'trendStyleEvening': "Evening gowns",
    'trendStyleModest': "Modest fashion",
    'trendStyleKids': "Kidswear",
    'trendOccasionWork': "Workwear",
    'trendOccasionWedding': "Wedding guest looks",
    'trendOccasionUniversity': "Campus outfits",
    'trendOccasionFamily': "Family gatherings",
  };

  static String get(String key) => values[key] ?? key;
}
